# Generated by Django 5.2.17 on 2026-09-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_options_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('hex', models.CharField(blank=True, max_length=7, verbose_name='Rang kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='trade_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Universal'), (2, 'Oziq-ovqat'), (3, 'Qurilish mollari'), (4, 'Kiyim-kechak va poyabzal'), (5, 'Farmasevtika'), (6, 'Texnika')], default=1, help_text='Mahsulot maydonlari va interfeys rangi shunga qarab moslashadi.', verbose_name='Savdo turi'),
        ),
        migrations.AddField(
            model_name='company',
            name='barcode_length',
            field=models.PositiveSmallIntegerField(default=13, help_text='Prefiks bilan birga umumiy belgilar soni (8-20).', verbose_name='Shtrix-kod uzunligi'),
        ),
        migrations.AddField(
            model_name='company',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text='Avtomatik yaratilgan kod shu bilan boshlanadi. Masalan: 200', max_length=10, verbose_name='Shtrix-kod prefiksi'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=150, verbose_name="Ta'sir etuvchi modda"),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Partiya / seriya'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ishlab chiqarilgan davlat'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dozasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dori shakli'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkak', 'Erkaklar'), ('ayol', 'Ayollar'), ('bola', 'Bolalar'), ('unisex', 'Uniseks')], max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=120, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name="Netto og'irlik (kg)"),
        ),
        migrations.AddField(
            model_name='product',
            name='package_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Qadoqdagi soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=80, verbose_name="Quvvat / texnik ko'rsatkich"),
        ),
        migrations.AddField(
            model_name='product',
            name='prescription_required',
            field=models.BooleanField(default=False, verbose_name="Retsept bo'yicha"),
        ),
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarilgan sana'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('yoz', 'Yozgi'), ('qish', 'Qishki'), ('demi', 'Demisezon'), ('universal', 'Mavsumsiz')], max_length=10, verbose_name='Mavsum'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Seriya raqami'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name="O'lcham"),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=150, verbose_name='Saqlash sharti'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kafolat (oy)'),
        ),
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Bir nechta filial biriktirilsa, xodim sozlamalardan filialni almashtira oladi.', related_name='staff', to='core.branch', verbose_name='Biriktirilgan filiallar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Hozir ishlayotgan filiali. Biriktirilgan filiallardan biri bo'ladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_staff', to='core.branch', verbose_name='Faol filial'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.color', verbose_name='Rang'),
        ),
    ]
