# Generated by Django 5.2.17 on 2026-09-19 02:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_color_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.Sh.')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Kassada avtomatik qo'llanadi.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Doimiy chegirma (%)')),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Qarzga olingan tovarlar summasi. To'lov qilinganda kamayadi.", max_digits=14, verbose_name='Qarz')),
                ('debt_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="0 bo'lsa cheklov yo'q.", max_digits=14, verbose_name='Qarz chegarasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Summa')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='core.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.customer', verbose_name='Mijoz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_payments', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan xodim')),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Chek raqami')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Chegirmasiz summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Chegirma')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Jami')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Jami summa ichidagi QQS ulushi.', max_digits=14, verbose_name='QQS')),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Foydani hisoblash uchun sotuv paytidagi tan narxlari yig'indisi.", max_digits=14, verbose_name='Tan narxi jami')),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Naqd'), (2, 'Plastik karta'), (3, "O'tkazma"), (4, 'Qarzga')], default=1, verbose_name="To'lov turi")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Berilgan pul')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Qaytim')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Qaytarilgan summa')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, "To'langan"), (2, 'Qisman qaytarilgan'), (3, 'Qaytarilgan')], default=1, verbose_name='Holat')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sana')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.branch', verbose_name='Filial')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Shtrix-kod')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Narxi')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Tan narxi')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Chegirma')),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Qaytarilgan soni')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='core.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale', verbose_name='Chek')),
            ],
            options={
                'verbose_name': 'Chek qatori',
                'verbose_name_plural': 'Chek qatorlari',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Kirim'), (2, 'Sotuv'), (3, 'Qaytarish'), (4, 'Tuzatish'), (5, 'Chiqim (yaroqsiz)')], verbose_name='Turi')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Musbat — qoldiq ortdi, manfiy — kamaydi.', max_digits=12, verbose_name="O'zgarish")),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Keyingi qoldiq')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='core.sale', verbose_name='Chek')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('branch', 'number'), name='unique_sale_number_per_branch'),
        ),
    ]
