# Generated by Django 5.2.17 on 2026-09-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_customerpayment_sale_saleitem_stockmovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list, verbose_name='Vektor')),
                ('source_hash', models.CharField(db_index=True, max_length=64, verbose_name='Matn nazorat summasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot vektori',
                'verbose_name_plural': 'Mahsulot vektorlari',
            },
        ),
    ]
