# Generated by Django 5.2.17 on 2026-09-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Sarlavha')),
                ('last_interaction_id', models.CharField(blank=True, max_length=128, verbose_name='Oxirgi javob id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Yangilangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI suhbat',
                'verbose_name_plural': 'AI suhbatlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Foydalanuvchi'), (2, 'AI'), (3, 'Xato')], verbose_name='Kim')),
                ('text', models.TextField(verbose_name='Matn')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Manbalar')),
                ('tables', models.JSONField(blank=True, default=list, verbose_name='Jadvallar')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Kirish tokenlari')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Chiqish tokenlari')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='Ketgan vaqt (ms)')),
                ('tool_calls', models.PositiveSmallIntegerField(default=0, verbose_name='Asbob chaqiruvlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation', verbose_name='Suhbat')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['pk'],
            },
        ),
    ]
