# Generated by Django 5.2.17 on 2026-09-21 04:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('tin', models.CharField(blank=True, max_length=20, verbose_name='STIR (INN)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Qarzga olingan tovarlar summasi.', max_digits=14, verbose_name='Bizning qarzimiz')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': "Ta'minotchi",
                'verbose_name_plural': "Ta'minotchilar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Qabul'), (2, 'Sotuv')], verbose_name='Turi')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Qoralama'), (2, 'Tasdiqlangan'), (3, 'Bekor qilingan')], default=1, verbose_name='Holat')),
                ('number', models.CharField(blank=True, max_length=64, verbose_name='Nakladnoy raqami')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Hujjat sanasi')),
                ('supplier_name', models.CharField(blank=True, help_text="AI o'qigan matn — ta'minotchini tanlashga yordam beradi.", max_length=200, verbose_name="Hujjatdagi ta'minotchi nomi")),
                ('file', models.FileField(blank=True, upload_to='waybills/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Asl fayl nomi')),
                ('on_credit', models.BooleanField(default=False, help_text="Qabulda — ta'minotchiga qarz yoziladi.", verbose_name='Qarzga')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('parse_tokens', models.PositiveIntegerField(default=0, verbose_name='Tahlil tokenlari')),
                ('parse_ms', models.PositiveIntegerField(default=0, verbose_name='Tahlil vaqti (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='core.branch', verbose_name='Filial')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_waybills', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_waybills', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='core.customer', verbose_name='Mijoz')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='core.sale', verbose_name='Yaratilgan chek')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='core.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': 'Nakladnoy',
                'verbose_name_plural': 'Nakladnoylar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Hujjatdagi nomi')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Shtrix-kod')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Narxi')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sotuv narxi (yangi mahsulot uchun)')),
                ('matched_by', models.CharField(blank=True, choices=[('barcode', 'Shtrix-kod'), ('name', 'Nomi'), ('semantic', 'Taxminiy'), ('manual', "Qo'lda"), ('', 'Topilmadi')], max_length=10, verbose_name='Qanday topildi')),
                ('match_score', models.FloatField(blank=True, null=True, verbose_name='Moslik')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_items', to='core.product', verbose_name='Mahsulot')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.waybill', verbose_name='Nakladnoy')),
            ],
            options={
                'verbose_name': 'Nakladnoy qatori',
                'verbose_name_plural': 'Nakladnoy qatorlari',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_supplier_per_company'),
        ),
    ]
